# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sistema.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

import sys
from os.path import dirname, realpath, join
import pandas as pd
import numpy as np
from statsmodels.tsa.ar_model import AutoReg

from tkinter import Tk
from tkinter.filedialog import askopenfilename

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 565)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bt_arquivo = QtWidgets.QPushButton(self.centralwidget)
        self.bt_arquivo.setGeometry(QtCore.QRect(660, 50, 75, 23))
        self.bt_arquivo.setObjectName("bt_arquivo")
        self.bt_predizer = QtWidgets.QPushButton(self.centralwidget)
        self.bt_predizer.setGeometry(QtCore.QRect(650, 470, 75, 23))
        self.bt_predizer.setObjectName("bt_predizer")
        self.txt_predicao = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_predicao.setGeometry(QtCore.QRect(20, 470, 591, 20))
        self.txt_predicao.setObjectName("txt_predicao")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txt_totalFaturado = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_totalFaturado.setGeometry(QtCore.QRect(440, 50, 161, 20))
        self.txt_totalFaturado.setObjectName("txt_totalFaturado")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 30, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.sp_colunas = QtWidgets.QSpinBox(self.centralwidget)
        self.sp_colunas.setGeometry(QtCore.QRect(610, 50, 42, 22))
        self.sp_colunas.setObjectName("sp_colunas")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(650, 90, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(650, 120, 130, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rb_media = QtWidgets.QRadioButton(self.layoutWidget)
        self.rb_media.setChecked(True)
        self.rb_media.setObjectName("rb_media")
        self.verticalLayout.addWidget(self.rb_media)
        self.rb_desvioPadrao = QtWidgets.QRadioButton(self.layoutWidget)
        self.rb_desvioPadrao.setObjectName("rb_desvioPadrao")
        self.verticalLayout.addWidget(self.rb_desvioPadrao)
        self.rb_mediaPonderada = QtWidgets.QRadioButton(self.layoutWidget)
        self.rb_mediaPonderada.setObjectName("rb_mediaPonderada")
        self.verticalLayout.addWidget(self.rb_mediaPonderada)
        self.rb_segregacaoDados = QtWidgets.QRadioButton(self.layoutWidget)
        self.rb_segregacaoDados.setObjectName("rb_segregacaoDados")
        self.verticalLayout.addWidget(self.rb_segregacaoDados)
        self.rb_regressaoDados = QtWidgets.QRadioButton(self.layoutWidget)
        self.rb_regressaoDados.setObjectName("rb_regressaoDados")
        self.verticalLayout.addWidget(self.rb_regressaoDados)
        self.rb_seriesTemporais = QtWidgets.QRadioButton(self.layoutWidget)
        self.rb_seriesTemporais.setObjectName("rb_seriesTemporais")
        self.verticalLayout.addWidget(self.rb_seriesTemporais)
        self.tb_faturamento = QtWidgets.QTableWidget(self.centralwidget)
        self.tb_faturamento.setGeometry(QtCore.QRect(20, 81, 591, 381))
        self.tb_faturamento.setObjectName("tb_faturamento")
        self.tb_faturamento.setColumnCount(3)
        self.tb_faturamento.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_faturamento.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_faturamento.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_faturamento.setHorizontalHeaderItem(2, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_arquivo.setText(_translate("MainWindow", "Arquivo"))
        self.bt_predizer.setText(_translate("MainWindow", "Predizer"))
        self.label.setText(_translate("MainWindow", "Predição de Faturamento"))
        self.label_2.setText(_translate("MainWindow", "Total Faturado"))
        self.label_3.setText(_translate("MainWindow", "Tipo de Predição"))
        self.rb_media.setText(_translate("MainWindow", "Média"))
        self.rb_desvioPadrao.setText(_translate("MainWindow", "Desvio Padrão"))
        self.rb_mediaPonderada.setText(_translate("MainWindow", "Média Ponderada"))
        self.rb_segregacaoDados.setText(_translate("MainWindow", "Segregação de Dados"))
        self.rb_regressaoDados.setText(_translate("MainWindow", "Regressão Linear"))
        self.rb_seriesTemporais.setText(_translate("MainWindow", "Séries Temporais"))
        item = self.tb_faturamento.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ano"))
        item = self.tb_faturamento.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mes"))
        item = self.tb_faturamento.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Faturamento"))

        self.bt_arquivo.clicked.connect(self.openFile)
        # self.bt_predizer.clicked.connect(self.predicao)

    def openFile(self):
        # Localiza o caminho do arquivo
        Tk().withdraw()
        path = askopenfilename()
        self.all_data = pd.read_csv(path)

        # Carrega o arquivo na tabela
        numColumn = self.sp_colunas.value()
        if numColumn == 0:
            numRows = len(self.all_data.index)
        else:
            numRows = numColumn
        self.tb_faturamento.setColumnCount(len(self.all_data.columns))
        self.tb_faturamento.setRowCount(numRows)
        self.tb_faturamento.setHorizontalHeaderLabels(self.all_data.columns)

        for i in range(numRows):
            for j in range(len(self.all_data.columns)):
                self.tb_faturamento.setItem(i, j, QtWidgets.QTableWidgetItem(str(self.all_data.iat[i, j])))
        
        self.tb_faturamento.resizeColumnsToContents()
        self.tb_faturamento.resizeRowsToContents

        # Soma do Faturamento
        soma_faturamento = str('R$%0.02f' %sum(self.all_data['Faturamento']))
        self.txt_totalFaturado.setText(soma_faturamento)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
